<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>
<?php foreach ($values as $term => $propertyData): ?>
    <!-- For each subsection (site\item\resource-values.phtml) -->
    <div class="single-property property d-flex align-items-start mb-4" id="<?php echo substr($term, strpos($term, ':')+1) ?>">
        <!-- subsection label (site\item\resource-values.phtml) -->
        <h4 class="property-header d-flex-inline col-4">
        <?php if ($propertyData['alternate_label']): ?>
            <!-- this label -->
        <?php echo $escape($propertyData['alternate_label']); ?>
        <?php else: ?>
            <!-- this label 2 -->
        <?php echo $escape($translate($propertyData['property']->label())); ?>
        <?php endif; ?>
        <?php if ('term' === $labelInfo): ?>
            <!-- this label 3 -->
        <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
            <!-- this label 4 -->
        <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
        <?php endif; ?>
        </h4>

        <!-- subsection value (site\item\resource-values.phtml) -->
        <div class="values col-8">
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            $valueType = $value->type();
            $class = ['value'];
            if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
            ?>
            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>
                <?php echo $value->asHtml(); ?>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
