<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>

<div class="h-100 d-flex px-4 py-3">
    <div class="col-12 col-lg-5 col-xl-4 px-0 ml-4" id="location-div">
        <!-- Adjust layout for image (site\item\show.phtml) -->
        <?php if (!$embedMedia && $itemMedia): ?>
        <div class="media-list position-relative">
            <?php foreach ($itemMedia as $media): ?>
                <?php echo $media->linkPretty(); ?>
            <?php endforeach; ?>

            <!-- Title (site\item\show.phtml) -->
            <div class="font-subsubheader d-flex justify-content-center position-absolute" id="location-title">
                <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
            </div>
        </div>
        <?php endif; ?>

        <div class="d-flex toggle-divs">
            <div class="single-toggle cursor-pointer col d-flex flex-column justify-content-center align-items-center text-center py-2 active"><i class="fas fa-lg fa-info-circle mb-1"></i> Info</div>
            <div class="single-toggle cursor-pointer col d-flex flex-column justify-content-center align-items-center text-center py-2"><i class="fas fa-lg fa-images mb-1"></i> Gallery</div>
            <div class="single-toggle cursor-pointer col d-flex flex-column justify-content-center align-items-center text-center py-2"><i class="fas fa-lg fa-star mb-1"></i> Key Events</div>
            <!--<div class="single-toggle cursor-pointer col d-flex flex-column justify-content-center align-items-center text-center py-2"><i class="fas fa-lg fa-bullhorn mb-1"></i> Happenings</div>-->
        </div>

        <!-- "Item" (site\item\show.phtml) -->
        <!--<h3><?php echo $translate('Item'); ?></h3>-->

        <div class="px-3 py-3" id="location-details-div">
            <?php $this->trigger('view.show.before'); ?>
            <?php if ($embedMedia && $itemMedia): ?>
                <div class="media-embeds">
                <?php foreach ($itemMedia as $media):
                    echo $media->render();
                endforeach;
                ?>
                </div>
            <?php endif; ?>

            <!-- Display Item values (site\item\show.phtml) -->
            <?php echo $item->displayValues(); ?>

            <!-- Adjust layout for item sets (site\item\show.phtml) -->
            <div class="property">
                <?php $itemSets = $item->itemSets(); ?>
                <?php if (count($itemSets) > 0): ?>
                    <h4><?php echo $translate('Item sets'); ?></h4>
                    <?php foreach ($itemSets as $itemSet): ?>
                        <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>

            <!--<?php if (($this->siteSetting('show_attached_pages', true)) && ($sitePages = $item->sitePages($site->id()))): ?>
            <div class="property">
                <h4><?php echo $translate('Site pages'); ?></h4>
                <div class="values">
                    <?php foreach ($sitePages as $sitePage): ?>
                    <div class="value"><?php echo $sitePage->link($sitePage->title()); ?></div>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php endif; ?>-->

            <?php
            $page = $this->params()->fromQuery('page', 1);
            $property = $this->params()->fromQuery('property');
            $subjectValues = $item->displaySubjectValues($page, 25, $property);
            ?>
            <?php if ($subjectValues): ?>
            <div id="item-linked">
                <h3><?php echo $translate('Linked resources'); ?></h3>
                <?php echo $subjectValues; ?>
            </div>
            <?php endif; ?>
        </div>

        <div class="btn btn-sm btn-outline-secondary cursor-pointer position-absolute" id="btn-return">
            <i class="fas fa-angle-double-left"></i> Back to Homepage
        </div>
    </div>
</div>

<?php $this->trigger('view.show.after'); ?>
