<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headLink()->appendStylesheet($this->assetUrl('css/bootstrap.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/custom.css'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/bootstrap.bundle.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/script.js'));
$this->headScript()->appendFile($this->assetUrl('js/fontawesome.js'));
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        
        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }
            
            a:active,
            a:hover {
                color: <?php echo $accentColor; ?>;
                opacity: .75;
            }
            <?php endif; ?>
        </style>
    </head>

    <!--<?php echo $this->htmlElement('body'); ?>-->
    <body class="h-100 page">
        <div class="h-100 d-none d-lg-block">
            <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
            <?php echo $userBar; ?>
            <header class="px-4 py-2 d-flex align-items-center">
                <div class="font-subheader px-0 ml-0 mr-3 d-flex align-items-center justify-content-center font-weight-bold" id="brand-logo"></div>
                <!--<h1 class="d-none">
                    <a href="<?php echo $site->url(); ?>" class="site-title">
                    <?php if ($this->themeSetting('logo')): ?>
                        <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                    <?php else: ?>
                        <?php echo $escape($siteTitle); ?>
                    <?php endif; ?>
                    </a>
                </h1>-->
                <!--<div id="search">
                    <?php echo $this->partial('common/search-form'); ?>
                </div>-->

                <nav class="ml-3 d-flex align-items-center">
                    <?php
                    echo $site->publicNav()->menu()->renderMenu(null, [
                        'maxDepth' => $this->themeSetting('nav_depth') - 1
                    ]);
                    ?>
                    <li class="d-flex align-items-center mx-3 pl-3 cursor-pointer">
                        <a href="https://google.com" target="_blank">Contribute Information! <i class="fas fa-external-link-alt"></i></a>
                    </li>
                    <li class="d-flex align-items-center mx-3 cursor-pointer" data-toggle="modal" data-target="#about-us">About SALTY</li>
                </nav>
            </header>
            <div class="h-100 position-relative" id="content" role="main">
                <div id="nav-div" class="d-flex position-relative">
                    <div class="d-flex flex-column align-items-center py-3" id="main-nav">
                        <div class="single-main-nav cursor-pointer mb-1 font-weight-bold d-flex justify-content-between align-items-center px-4 py-2 mb-2" data-view-type="year">
                            <div class="d-flex align-items-center">
                                <i class="single-nav-icon fas fa-calendar-day fa-lg mr-2"></i> <span class="mx-1">YEAR</span>
                            </div>
                            <div>
                                <i class="fas fa-angle-right"></i>
                            </div>
                        </div>
                        <div class="single-main-nav cursor-pointer mb-1 font-weight-bold d-flex justify-content-between align-items-center px-4 py-2 mb-2" data-view-type="location">
                            <div class="d-flex align-items-center">
                                <i class="single-nav-icon fas fa-map-signs fa-lg mr-2"></i> <span class="mx-1">PLACE</span>
                            </div>
                            <div>
                                <i class="fas fa-angle-right"></i>
                            </div>
                        </div>
                    </div>
                    <div class="sub-nav position-absolute h-100 d-flex flex-column py-4" id="sub-nav-year">
                        <div class="w-100">
                            <div class="single-sub-nav cursor-pointer px-2 position-relative d-flex justify-content-center align-items-center">
                                <div class="single-year-select stretched-link active" data-year-view="default">Default Map</div>
                            </div>
                            <hr class="w-50 border-top border-light mt-4">
                            <?php 
                                $years = array("Year 1975");

                                foreach($years as $key=>$value) {
                            ?>
                            <div class="single-sub-nav cursor-pointer px-2 position-relative d-flex justify-content-center align-items-center">
                                <div class="single-year-select stretched-link" data-year-view="<?php echo($key + 1) ?>"><?php echo($value) ?></div>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="sub-nav font-form position-absolute h-100 d-flex flex-column py-4" id="sub-nav-location">
                        <div class="form-group px-3 mb-0">
                            <input type="text" class="form-control" placeholder="Search Place" id="search-locations">
                            <hr class="w-50 border-top border-light mt-4">
                        </div>

                        <?php 
                            $items = $this->api()->search('items', ['site_id'=>1, 'sort_by'=>'dcterms:title', 'sort_order'=>'asc', 'is_public'=>true])->getContent();

                            foreach($items as $item) {
                        ?>
                        <div class="single-location d-flex mb-3 px-3" data-location-name="<?php echo $item->displayTitle() ?>">
                            <div class="w-100">
                                <div class="single-sub-nav cursor-pointer px-2 position-relative d-flex align-items-center">
                                    <?php echo $item->link($item->displayTitle(), null, ["class" => "stretched-link"]) ?>
                                </div>
                            </div>
                        </div>

                        <?php } ?>
                    </div>
                    <footer class="p-0">
                        <?php if ($footerContent = $this->themeSetting('footer')): ?>
                        <?php echo $footerContent; ?>
                        <?php else: ?>
                            <?php echo $this->translate('Powered by Omeka S'); ?>
                        <?php endif; ?>
                    </footer>
                </div>
                <?php echo $this->content; ?>
            </div>
        </div>
        <div class="modal fade" id="about-us" tabindex="-1" role="dialog" aria-labelledby="aboutUsLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="aboutUsLabel">About Us</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="font-form modal-body">
                        <p class="mb-4">The Singapore Architecture Literacy Network (SALTY) is a digital initiative that aims to promote the understanding and appreciation of Singapore’s built heritage. By indexing and consolidating available information on Singapore’s heritage architecture, SALTY seeks to build a framework for public understanding of Singapore’s unique heritage(s).</p>

                        <div class="d-flex flex-column mb-3">
                            <div class="d-flex mb-3">
                                <div class="col-4 pl-0 font-weight-bold">Initiated by</div>
                                <div class="col-8 px-0">
                                    <p class="mb-2">Associate Professor Johannes Widodo<br/><span class="font-small">(NUS Department of Architecture)</span></p>
                                    <p class="mb-1">Mr. Fauzy Ismail</p>
                                </div>
                            </div>
                            <div class="d-flex mb-3">
                                <div class="col-4 pl-0 font-weight-bold">Research Assistant</div>
                                <div class="col-8 px-0">
                                    <p class="mb-1">Mr. Alfonse Chiu</p>
                                </div>
                            </div>
                            <div class="d-flex mb-3">
                                <div class="col-4 pl-0 font-weight-bold">Additional Support</div>
                                <div class="col-8 px-0">
                                    <p class="mb-2">Dr. Natalie Pang<br/><span class="font-small">(NUS Department of Communications and New Media)</span></p>
                                    <p class="mb-1">Mr. Gaetan Boisson<br/><span class="font-small">(NUS Library Digital Scholarly Communications)</span></p>
                                </div>
                            </div>
                            <div class="d-flex mb-3">
                                <div class="col-4 pl-0 font-weight-bold">Platform Developer</div>
                                <div class="col-8 px-0">
                                    <p class="mb-2">Dr. Yen Ching-Chiuan<br/><span class="font-small">(Keio-NUS CUTE Centre)</span></p>
                                    <p class="mb-1">Mr. Justin Eng<br/><span class="font-small">(Keio-NUS CUTE Centre)</span></p>
                                </div>
                            </div>
                            <div class="d-flex mb-3">
                                <div class="col-4 pl-0 font-weight-bold">Supported by</div>
                                <div class="col-8 px-0">
                                    <div id="nhb-logo"></div>
                                </div>
                            </div>
                        </div>

                        <p class="font-small mb-0">
                            &copy; 2022 Singapore Architecture Literacy Network (SALTY). All Rights Reserved.<br/>
                            All content copyright belongs to original authors and are used for non-commercial, educational purposes under Fair Use.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="h-100 d-block d-lg-none d-flex flex-column align-items-center justify-content-center text-center px-3">
            <h1 class="font-large font-weight-bold mb-4">Oops!</h1>
            <p class="font-subsubheader">Your current browser resolution is not supported. Only browser widths 992px and larger can view this site.</p>
        </div>
    </body>
</html>